//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.30 at 02:13:59 PM MEZ 
//


package org.geojsf.xml.geoserver;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.geojsf.org/geoserver}dbLayer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbLayer"
})
@XmlRootElement(name = "layer")
public class Layer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected DbLayer dbLayer;

    /**
     * Gets the value of the dbLayer property.
     * 
     * @return
     *     possible object is
     *     {@link DbLayer }
     *     
     */
    public DbLayer getDbLayer() {
        return dbLayer;
    }

    /**
     * Sets the value of the dbLayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbLayer }
     *     
     */
    public void setDbLayer(DbLayer value) {
        this.dbLayer = value;
    }

    public boolean isSetDbLayer() {
        return (this.dbLayer!= null);
    }

}
