//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.25 at 02:50:03 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://geojsf.sf.net/geojsf")
package org.geojsf.xml.geojsf;
