alter table GeoSldJtDescription add constraint uk_GeoSldJtDescription_description unique (description_id);
alter table GeoSldJtLang add constraint uk_GeoSldJtLang_lang unique (lang_id);
alter table GeoSldJtRule add constraint UK_55jmhrhr58m7y3goh51t3x9mu unique (rule_id);
alter table GeoSldRuleJtDescription add constraint uk_GeoSldRuleJtDescription_description unique (description_id);
alter table GeoSldRuleJtLang add constraint uk_GeoSldRuleJtLang_lang unique (lang_id);
alter table GeoSldTemplateJtDescription add constraint uk_GeoSldTemplateJtDescription_description unique (description_id);
alter table GeoSldTemplateJtLang add constraint uk_GeoSldTemplateJtLang_lang unique (lang_id);
alter table GeoSld add constraint fk_GeoSld_attribute foreign key (attribute_id) references IoLabelAttribute;
alter table GeoSld add constraint fk_GeoSld_entity foreign key (entity_id) references IoLabelEntity;
alter table GeoSld add constraint fk_GeoSld_template foreign key (template_id) references GeoSldTemplate;
alter table GeoSld add constraint fk_GeoSld_type foreign key (type_id) references IoStatus;
alter table GeoSldJtDescription add constraint fk_GeoSldJtDescription_lang foreign key (description_id) references IoDescription;
alter table GeoSldJtDescription add constraint fk_GeoSldJtDescription_sld foreign key (sld_id) references GeoSld;
alter table GeoSldJtLang add constraint fk_GeoSldJtLang_lang foreign key (lang_id) references IoLang;
alter table GeoSldJtLang add constraint fk_GeoSldJtLang_sld foreign key (sld_id) references GeoSld;
alter table GeoSldJtRule add constraint FKs1knitwygx9gfhgsi06kr0klo foreign key (rule_id) references GeoSldRule;
alter table GeoSldJtRule add constraint FK1bb1qi995vffu7x8flk3pvpkp foreign key (sld_id) references GeoSld;
alter table GeoSldRule add constraint fk_GeoSldRule_graphic foreign key (graphic_id) references IoGraphic;
alter table GeoSldRuleJtDescription add constraint fk_GeoSldRuleJtDescription_lang foreign key (description_id) references IoDescription;
alter table GeoSldRuleJtDescription add constraint fk_GeoSldRuleJtDescription_sld foreign key (rule_id) references GeoSldRule;
alter table GeoSldRuleJtLang add constraint fk_GeoSldRuleJtLang_lang foreign key (lang_id) references IoLang;
alter table GeoSldRuleJtLang add constraint fk_GeoSldRuleJtLang_sld foreign key (rule_id) references GeoSldRule;
alter table GeoSldTemplateJtDescription add constraint fk_GeoSldTemplateJtDescription_lang foreign key (description_id) references IoDescription;
alter table GeoSldTemplateJtDescription add constraint fk_GeoSldTemplateJtDescription_sld foreign key (template_id) references GeoSldTemplate;
alter table GeoSldTemplateJtLang add constraint fk_GeoSldRuleJtLang_lang foreign key (lang_id) references IoLang;
alter table GeoSldTemplateJtLang add constraint fk_GeoSldTemplateJtLang_sld foreign key (template_id) references GeoSldTemplate;