alter table GeoSld_Rule add constraint UK_pk36dbi44w5s50rca69u1urt2 unique (rule);
alter table GeoSldJtDescription add constraint UK_ny4km0p4e9im92vb6tcshv0j7 unique (description_id);
alter table GeoSldJtLang add constraint UK_t3sp25u3wfa3705488u5y5uyt unique (lang_id);
alter table GeoSldRule_IoDescription add constraint UK_8jkk5bplck3oyyrtksrh8c4r6 unique (description_id);
alter table GeoSldRule_IoLang add constraint UK_s8a4wrobco0hh88txpkh9a4d0 unique (name_id);
alter table GeoSldTemplate_IoDescription add constraint UK_i67xyvodppgj9xtyjablhp1iy unique (description_id);
alter table GeoSldTemplate_IoLang add constraint UK_6075jbv5h9c1pfnjxfrnik8fh unique (name_id);
alter table GeoSld add constraint FK61wls7o1hf4xcn6srgw6exv0a foreign key (attribute_id) references IoLabelAttribute;
alter table GeoSld add constraint FKcs4gtwkhaol2g2vj21teiiwbj foreign key (entity_id) references IoLabelEntity;
alter table GeoSld add constraint FKc15ce6pvlxs97kttbxpsnfflv foreign key (template_id) references GeoSldTemplate;
alter table GeoSld add constraint FK4n7abjtxftbbqgegwsqqv9qu5 foreign key (type_id) references IoStatus;
alter table GeoSld_Rule add constraint FKmr5sqngo6618i9gwp3o3s7dx foreign key (rule) references GeoSldRule;
alter table GeoSld_Rule add constraint FKld7ulcslhmefynyo0o8rh9nj6 foreign key (sld) references GeoSld;
alter table GeoSldJtDescription add constraint FKsxfxowtq4t7c3jnj19mks3lc7 foreign key (description_id) references IoDescription;
alter table GeoSldJtDescription add constraint FK9i9iedyjckvomgr27vpdt5vlo foreign key (sld_id) references GeoSld;
alter table GeoSldJtLang add constraint FK1rukxkc2syx108rkeflecsrwi foreign key (lang_id) references IoLang;
alter table GeoSldJtLang add constraint FKlgnlbmoj1asqjvkbwemlrk991 foreign key (sld_id) references GeoSld;
alter table GeoSldRule add constraint FKt2ugy9gywy4j8qgx6k0wmx6jp foreign key (graphic_id) references IoGraphic;
alter table GeoSldRule_IoDescription add constraint FKcf93v1a4l0dpxypnub4a7hxu6 foreign key (description_id) references IoDescription;
alter table GeoSldRule_IoDescription add constraint FK1h40wflbxppr9ey1hd1bw782a foreign key (GeoSldRule_id) references GeoSldRule;
alter table GeoSldRule_IoLang add constraint FKka8k0iyodrofrwxxlsrywpjhy foreign key (name_id) references IoLang;
alter table GeoSldRule_IoLang add constraint FKdxn2o4jtcwdv6c8cuxlfkhlcq foreign key (GeoSldRule_id) references GeoSldRule;
alter table GeoSldTemplate_IoDescription add constraint FKibaytemybxhct5o1s3tmpfxc foreign key (description_id) references IoDescription;
alter table GeoSldTemplate_IoDescription add constraint FKfoxi52itg6u6nlhctnx4s4ds3 foreign key (GeoSldTemplate_id) references GeoSldTemplate;
alter table GeoSldTemplate_IoLang add constraint FKbct45w5vesf63l8lpiuuvjmki foreign key (name_id) references IoLang;
alter table GeoSldTemplate_IoLang add constraint FK3nuim0ukq4f0h1jfxpk93cvuj foreign key (GeoSldTemplate_id) references GeoSldTemplate;
