create table GeoSld (id  bigserial not null, library boolean, statusAttribute varchar(255), statusClass varchar(255), attribute_id int8, entity_id int8, template_id int8, type_id int8, primary key (id));
create table GeoSld_Rule (sld int8 not null, rule int8 not null);
create table GeoSldJtDescription (sld_id int8 not null, description_id int8 not null, primary key (sld_id, description_id));
create table GeoSldJtLang (sld_id int8 not null, lang_id int8 not null, primary key (sld_id, lang_id));
create table GeoSldRule (id  bigserial not null, lowerBound float8, position int4 not null, upperBound float8, graphic_id int8, primary key (id));
create table GeoSldRule_IoDescription (GeoSldRule_id int8 not null, description_id int8 not null, primary key (GeoSldRule_id, description_id));
create table GeoSldRule_IoLang (GeoSldRule_id int8 not null, name_id int8 not null, primary key (GeoSldRule_id, name_id));
create table GeoSldTemplate (id  bigserial not null, code varchar(255), xml text, primary key (id));
create table GeoSldTemplate_IoDescription (GeoSldTemplate_id int8 not null, description_id int8 not null, primary key (GeoSldTemplate_id, description_id));
create table GeoSldTemplate_IoLang (GeoSldTemplate_id int8 not null, name_id int8 not null, primary key (GeoSldTemplate_id, name_id));