//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.26 at 07:48:40 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengis.net/gml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sf.geojsf.xml.gml;
